name: stock-correction-bot

include:
  - services/docker-compose.yml

services:
  mcp:
    build:
      context: ./mcp
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://api-gateway:80
    networks:
      - mock-net
    depends_on:
      - api-gateway

  chatapp:
    build:
      context: ./simple-chatapp
    ports:
      - "3001:3001"
    environment:
      - STOCK_API_BASE_URL=http://api-gateway:80
      - MCP_HOST=mcp:3000
    networks:
      - mock-net
    depends_on:
      - mcp
      - api-gateway
